apiVersion: v1
kind: Service
metadata:
   name: f5helloworld-svc
   labels:
     cis.f5.com/as3-tenant: f5helloworld
     cis.f5.com/as3-app: f5helloworld
     cis.f5.com/as3-pool: ingress_pool
spec:
   type: NodePort
   ports:
   - port: 80
     targetPort: 8080
     protocol: TCP
     name: http
   selector:
     app: f5helloworld